- name: Sync Assets via API
  run: |
    # 获取上游 Release 信息
    UPSTREAM_REPO="Ackites/KillWxapkg"
    LATEST_RELEASE=$(curl -s "https://api.github.com/repos/$UPSTREAM_REPO/releases/latest")
    ASSET_URLS=$(echo "$LATEST_RELEASE" | jq -r '.assets[].browser_download_url')

    # 下载并上传到当前仓库
    for url in $ASSET_URLS; do
      wget $url
      gh release upload latest $(basename $url) --clobber
    done
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
