name: Sync Upstream Releases

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Tags
        run: |
          git remote add upstream https://github.com/Ackites/KillWxapkg.git
          git fetch upstream --tags
          git push origin --tags

      - name: Get Latest Upstream Release
        id: get-release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Automatically synced from upstream"
          prerelease: false
          draft: false
          tag: latest  # 或从上游获取的标签

      - name: Download and Upload Assets
        run: |
          # 下载上游 Assets（示例：通过 API）
          ASSETS_URL=$(curl -s https://api.github.com/repos/Ackites/KillWxapkg/releases/latest | jq -r '.assets[].browser_download_url')
          for url in $ASSETS_URL; do
            wget $url
            gh release upload ${{ steps.get-release.outputs.id }} $(basename $url)
          done
